# Generated by Django 6.0.5 on 2026-06-22 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='new_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='old_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='target_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(max_length=300),
        ),
    ]
