# Generated by Django 6.0.5 on 2026-06-09 21:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='budget',
            name='unique_user_budget',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='category_id',
            new_name='category',
        ),
        migrations.AddConstraint(
            model_name='budget',
            constraint=models.UniqueConstraint(fields=('user', 'category', 'start_date', 'end_date'), name='unique_user_budget'),
        ),
    ]
