# Generated by Django 6.0.5 on 2026-05-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_verified_usersocialaccount'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usersocialaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
